# Generated by Django 3.1.4 on 2020-12-29 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 19, 41, 17, 312533), verbose_name='date published'),
        ),
    ]
